### ISSUE TITLE
guard-test with simplecov doesn't report coverage

### ISSUE THREAD

**Issue by jmthomas** [guard/guard-test#44]
I have several specs and several unit tests for a library I've developing. I have both guard-spec and guard-test installed and all my specs and tests run appropriately. However, I only get SimpleCov coverage data for my specs. It says it is generating coverage for Unit Tests but all I get is the method definitions as if it parsed the files but didn't run them.

When I run an individual test or my rake task that runs all the specs and test I get the coverage I expect.

My Guardfile:

```
guard :bundler do
  watch('Gemfile')
end

guard :test do
  watch(%r{^test/.+_test\.rb$})
  watch(%r{^lib/(.+)\.rb$})       { |m| "test/#{m[1].split('/')[-1]}_test.rb" }
  watch('test/test_helper.rb')    { 'test' }
end

guard :rspec do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})       { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^lib/tools/(.+)\.rb$}) { |m| "spec/tools/#{m[1].split('/')[-1]}_spec.rb" }
  watch('spec/spec_helper.rb')    { 'spec' }
end
```

My test_helper.rb

```
# Only require simplecov for Ruby 1.9 or greater
if RUBY_VERSION.split('.')[1].to_i >= 9
  require 'simplecov'
  SimpleCov.start do
    add_filter '/test/'
  end
end
require 'test/unit'
```

Using ruby v1.9.3p392, guard v1.8.0, guard-test v1.0.0, simplecov v0.7.1

**Comment by KjellMorgenstern** [comment]
I ran into the same behavior today (incomplete coverage when tests are run with guard). The problem was that guard requires minitest/autorun by default, which causes the coverage report to be finished early.
This could be solved by configuring guard:
`guard :minitest, autorun: false do
...
`
Just mentioning it here because this thread was the first result when I googled the issue.
